name: Streamlit App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Streamlit Sharing
      env:
        STREAMLIT_SHARING_URL: ${{ secrets.STREAMLIT_SHARING_URL }}
      run: |
        pip install streamlit-sharing
        streamlit run --server.port 8501 --server.headless true stock_data_collector.py &
        sleep 10
        curl -s $STREAMLIT_SHARING_URL > url.txt
        echo "Streamlit app URL: $(cat url.txt)"
        echo "STREAMLIT_URL=$(cat url.txt)" >> $GITHUB_ENV

    - name: Create GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Streamlit app deployed successfully.
          URL: ${{ env.STREAMLIT_URL }}
        draft: false
        prerelease: false
